name: CI

on: [push]

jobs:
  sast_scan:
    name: Run_Bandit_Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout_Code
      uses: actions/checkout@v2

    - name: Set_Up_Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install_Bandit
      run: pip install bandit

    - name: Run_Bandit_Scan
      run: bandit -ll -ii -r . -f json -o bandit-report.json

    - name: Upload_Artifact
      uses: actions/upload-artifact@v3
      if: always()
      with:
       name: bandit-findings
       path: bandit-report.json
  image_scan:
    name: Build_Image_and_Run_Image_Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout_Code
      uses: actions/checkout@v2

    - name: Set_Up_Docker
      uses: docker/setup-buildx-action@v3.0.0
      with:
       docker_version: '20.10.7'

    - name: Build_Docker_Image
      run: docker build -f Dockerfile -t myapp:latest .
       
  #  - name: Docker_Scout_Scan
  #    run: |
   #     curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
    #    sh install-scout.sh

     #   echo ${{ secrets.REPO_PWD }} | docker login -u ${{ secrets.REPO_USR }} --password-stdin
        
      #  docker scout quickview
       # docker scout cves 

    - name: Docker_Scout_Scan
      uses: docker/scout-action@v1.3.0
      with:
        dockerhub-user: ${{ secrets.REPO_USR }}
        dockerhub-password: ${{ secrets.REPO_PWD }}
        command: quickview, cves

   
