name: CI

on: [push]

jobs:
  sast_scan:
    name: Run_Bandit_Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout_Code
      uses: actions/checkout@v2

    - name: Set_Up_Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install_Bandit
      run: pip install bandit

    - name: Run_Bandit_Scan
      run: bandit -ll -ii -r .
